# Generated by Django 5.2.6 on 2025-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
