# Generated by Django 5.2.6 on 2025-10-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_has_verified_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_verified_email',
        ),
    ]
