# Generated by Django 5.2.6 on 2025-10-18 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_active'),
    ]

    operations = [
    ]
