# Generated by Django 5.2.6 on 2025-10-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_uuid_alter_profile_id'),
    ]

    operations = [
    ]
