# Generated by Django 5.2.6 on 2025-10-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_id_alter_profile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
    ]
