# Generated by Django 5.2.6 on 2025-10-31 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_id_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.profile'),
        ),
    ]
