# Generated by Django 5.2.6 on 2025-10-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_shipped_at_order_stock_debited_and_more'),
        ('products', '0006_product_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='products.product'),
            preserve_default=False,
        ),
    ]
