# Generated by Django 5.2.6 on 2025-10-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
