# Generated by Django 5.2.6 on 2025-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
