# Generated by Django 5.2.6 on 2025-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_channel_order_payment_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_channel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_provider',
        ),
    ]
