# Generated by Django 5.2.6 on 2025-11-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='epaka_label_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='epaka_order_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
