# Generated by Django 5.2.6 on 2025-11-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_epaka_label_number_order_epaka_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('inpost', 'InPost'), ('other', 'Kurier (Epaka – inny)')], default='inpost', max_length=20),
        ),
    ]
