# Generated by Django 5.2.6 on 2025-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('inpost_courier', 'InPost Courier'), ('dpd_courier', 'DPD Courier'), ('inpost_locker', 'InPost Locker'), ('pickup', 'Pickup')], default='inpost_courier', max_length=20),
        ),
    ]
