# Generated by Django 5.2.6 on 2025-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inpost_locker_code',
            field=models.CharField(blank=True, help_text='Kod paczkomatu InPost (np. WAW01N)', max_length=32),
        ),
    ]
