# Generated by Django 5.2.6 on 2025-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_inpost_locker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p24_order_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='p24_session_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='p24_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
