# Generated by Django 5.2.6 on 2026-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_epakatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='epaka_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='epaka_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_size',
            field=models.CharField(blank=True, choices=[('', '— wybierz —'), ('S', 'S (mała)'), ('M', 'M (średnia)'), ('L', 'L (duża)')], default='', help_text='Wybierz rozmiar/gabaryt przed wysłaniem do ePaki.', max_length=2),
        ),
    ]
