# Generated by Django 5.2.6 on 2026-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_epaka_last_error_order_epaka_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('percent', models.PositiveIntegerField(default=0, help_text='0-100 (%)')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='package_size',
            field=models.CharField(blank=True, choices=[('', '— wybierz —'), ('1', '1) 17×20×20 cm (do 2 kg)'), ('2', '2) 25×20×20 cm (do 5 kg)'), ('3', '3) 35×25×15 cm (do 7 kg)'), ('4', '4) 35×35×30 cm (do 10 kg)'), ('5', '5) 45×45×45 cm (do 20 kg)')], default='', max_length=2),
        ),
    ]
