# Generated by Django 5.2.6 on 2026-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_size',
            field=models.CharField(blank=True, choices=[('', '— wybierz —'), ('1', '1) 17×20×20 cm (do 1 kg)'), ('2', '2) 25×20×20 cm (do 4 kg)'), ('3', '3) 35×25×15 cm (do 6 kg)'), ('4', '4) 35×35×30 cm (do 10 kg)'), ('5', '5) 45×45×45 cm (do 15 kg)')], default='', max_length=2),
        ),
    ]
