# Generated by Django 5.2.6 on 2025-09-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('product_info', models.CharField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_vat', models.CharField(max_length=10)),
                ('product_type', models.CharField(choices=[('spozywcze', 'Spozywcze'), ('suplementy', 'Suplementy'), ('kosmetyki', 'Kosmetyki'), ('masci', 'Masci'), ('ziola', 'Ziola'), ('inne', 'Inne')], default='spozywcze', max_length=20)),
                ('product_ingredients', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
