# Generated by Django 5.2.6 on 2025-09-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ingredients',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('spozywcze', 'Spożywcze'), ('suplementy', 'Suplementy'), ('kosmetyki', 'Kosmetyki'), ('masci', 'Maści'), ('ziola', 'Zioła'), ('inne', 'Inne')], default='spozywcze', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vat',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('8', '8%'), ('23', '23%')], default='8', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
