# Generated by Django 5.2.6 on 2025-09-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_question_choice_product_product_product_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
