# Generated by Django 5.2.6 on 2025-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('spozywcze', 'Spożywcze'), ('suplementy', 'Suplementy'), ('kosmetyki do włosów', 'Kosmetyki do włosów'), ('kosmetyki do ciała', 'Kosmetyki do ciała'), ('kosmetyki do twarzy', 'Kosmetyki do twarzy'), ('masci', 'Maści'), ('ziola', 'Zioła'), ('inne', 'Inne')], default='spozywcze', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
