# Generated by Django 5.2.6 on 2025-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
