# Generated by Django 5.2.6 on 2025-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_new_product_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, default='https://szamankasklep.pl/static/img/placeholder.jpg', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
