# Generated by Django 5.2.6 on 2025-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_image_product_product_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
