# Generated by Django 5.2.6 on 2025-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, default='/static/products/images/default-image11.jpg', null=True),
        ),
    ]
