# Generated by Django 5.2.6 on 2025-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, default='https://szamankasklep.pl/static/images/placeholder.jpg', null=True),
        ),
    ]
