# Generated by Django 5.2.6 on 2025-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, default='static/products/images/default-image11.jpg', null=True),
        ),
    ]
