# Generated by Django 5.2.6 on 2026-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
