# Generated by Django 5.2.6 on 2026-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_file',
            field=models.ImageField(blank=True, default='products/images/default-image.png', null=True, upload_to='products/images/'),
        ),
    ]
